//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnWS.Entity
{
    using System;
    using System.Collections.Generic;
    
    using Repository;
    public partial class T_S_User:EntityBase,IAuditableEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_S_User()
        {
            this.T_S_User_Role = new HashSet<T_S_User_Role>();
            this.ZY_Session = new HashSet<ZY_Session>();
            this.ZY_Shop = new HashSet<ZY_Shop>();
        }
    
        public System.Guid UserId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public int Source { get; set; }
        public string OpenId { get; set; }
        public string AccessToken { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int VersionNo { get; set; }
        public System.Guid TransactionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_S_User_Role> T_S_User_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZY_Session> ZY_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZY_Shop> ZY_Shop { get; set; }
    }
}
