//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnWS.Entity
{
    using System;
    using System.Collections.Generic;
    
    using Repository;
    public partial class ZY_Booked_Position:EntityBase,IAuditableEntity
    {
        public System.Guid Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public System.Guid DeskId { get; set; }
        public string Position { get; set; }
        public bool IsInternal { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public string CustomerOpenId { get; set; }
        public int VersionNo { get; set; }
        public System.Guid TransactionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    
        public virtual ZY_Customer ZY_Customer { get; set; }
        public virtual ZY_Order ZY_Order { get; set; }
        public virtual ZY_Shop_Desk ZY_Shop_Desk { get; set; }
    }
}
