//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnWS.Entity
{
    using System;
    using System.Collections.Generic;
    
    using Repository;
    public partial class ZY_Order:EntityBase,IAuditableEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZY_Order()
        {
            this.ZY_Booked_Position = new HashSet<ZY_Booked_Position>();
        }
    
        public System.Guid OrderId { get; set; }
        public string CustomerOpenId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
        public decimal Amount { get; set; }
        public int VersionNo { get; set; }
        public System.Guid TransactionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string Prepay_id { get; set; }
        public bool IsInternal { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZY_Booked_Position> ZY_Booked_Position { get; set; }
        public virtual ZY_Customer ZY_Customer { get; set; }
    }
}
