

CREATE TABLE [dbo].[Pay](
	[Id] [uniqueidentifier] NOT NULL,
	return_code nvarchar(256) null,
	return_msg nvarchar(256) null,
	appid nvarchar(256) null,
	mch_id nvarchar(256) null,
	device_info nvarchar(256) null,
	nonce_str nvarchar(256) null,
	sign nvarchar(256) null,
	sign_type nvarchar(256) null,
	result_code nvarchar(256) null,
	err_code nvarchar(256) null,
	err_code_des nvarchar(256) null,
	openid nvarchar(256) null,
	is_subscribe nvarchar(256) null,
	trade_type nvarchar(256) null,
	bank_type nvarchar(256) null,
	total_fee nvarchar(256) null,
	settlement_total_fee nvarchar(256) null,
	fee_type nvarchar(256) null,
	cash_fee nvarchar(256) null,
	cash_fee_type nvarchar(256) null,
	coupon_fee nvarchar(256) null,
	coupon_count nvarchar(256) null,
	--coupon_type_$n nvarchar(256) null,
	--coupon_id_$n nvarchar(256) null,
	--coupon_fee_$n nvarchar(256) null,
	transaction_id nvarchar(256) null,
	out_trade_no nvarchar(256) null,
	attach nvarchar(256) null,
	time_end nvarchar(256) null,
	[VersionNo] [int] NOT NULL,
	[TransactionId] [uniqueidentifier] NOT NULL,
	[CreatedBy] [varchar](128) NOT NULL,
	[CreatedTime] [datetime] NOT NULL,
	[UpdatedBy] [varchar](128) NOT NULL,
	[UpdatedTime] [datetime] NOT NULL,
)


select NEWID()